name = "CND"
license = "Copyright © CLoud NYNE Design, LLC"
description = "A one page portfolio for freelancers, programmers and designers."
tags = ["portfolio", "showcase", "skills", "clients", "contact form"]
features = ["about section with skill rating", "stylish portfolio with slider", "carousel for client's quotes", "contact form"]
min_version = 0.14

[author]
  name = "ThatGuyCND"
  homepage = "//github.com/ThatGuyCND"
